name: Pr workflow

on: 
  push: 
    branches:
      - main
    paths-ignore:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '>=1.22'
          check-latest: true

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1

  audit:
      runs-on: ubuntu-20.04
      steps:
          - uses: actions/checkout@v2
      
          - name: Set up Go
            uses: actions/setup-go@v2
            with:
              go-version: 1.17
      
          - name: Verify dependencies
            run: go mod verify
          
          - name: Build
            run: go build -v ./...
      
          - name: Run go vet
            run: go vet ./...
      
          - name: Install staticcheck
            run: go install honnef.co/go/tools/cmd/staticcheck@latest
      
          - name: Run staticcheck
            run: staticcheck ./...
      
          - name: Install golint
            run: go install golang.org/x/lint/golint@latest
      
          - name: Run golint
            run: golint ./...
      
          - name: Run tests
            run: go test -race -vet=off ./...
      
      
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go
          queries: security-and-quality

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  greetings:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting to the Contributors
        run: |
          echo "Hello, contributors! Thank you for your hard work and dedication. Your contributions are greatly appreciated!"
          echo "Keep up the great work!"
          echo "Best regards,"
          echo "The Team"
      

        

  